/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/birth-chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get birth chart (D1 Rashi chart) - Kundli Calculator API
         * @description Calculate complete Vedic birth chart (Janam Kundli, natal chart) with all 9 planetary positions (Sun through Ketu) plus Ascendant (Lagna). Kundli calculator API for astrology apps, matrimonial sites. Returns accurate graha positions grouped by zodiac signs (rashis) with nakshatra details and pada. Perfect for kundli generation, horoscope matching, and Vedic astrology software integration.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BirthChartRequest"];
                };
            };
            responses: {
                /** @description Successful birth chart calculation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BirthChartResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/navamsa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Navamsa chart (D9) - Marriage Compatibility Calculator
         * @description Calculate Navamsa (D9 divisional chart) for marriage compatibility analysis, spouse prediction, and spiritual life assessment. Navamsa calculator API reveals planetary strength in married life. Each planet's position is divided into 9 parts for accurate marriage astrology. Detects Vargottama planets (exalted status). Essential for matrimonial matching, relationship prediction, and marital harmony analysis in Vedic astrology.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["NavamsaRequest"];
                };
            };
            responses: {
                /** @description Successful Navamsa chart calculation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NavamsaResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/compatibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate compatibility score - Gun Milan API (Ashtakoot Matching)
         * @description Calculate detailed Ashtakoot compatibility (Gun Milan) for kundli matching between two people. Marriage compatibility API for matrimonial sites and astrology apps. Returns accurate 36-point Guna Milan scale with breakdown: Nakshatra, Gana, Yoni, Rashi Lord, Vasya, Tara, Nadi, Bhakoot. Perfect for kundli matching for marriage, horoscope compatibility check, and Vedic matchmaking services.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CompatibilityRequest"];
                };
            };
            responses: {
                /** @description Successful compatibility calculation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CompatibilityResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planetary-positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get planetary positions - Graha Positions API
         * @description Get simplified planetary positions (graha positions) for all 9 planets (Sun through Ketu) plus Ascendant (Lagna). Real-time planet transit calculator for Vedic astrology. Navagraha positions API with nakshatra, pada, and rashi details. Faster response for basic planetary data without full chart structure. Perfect for planetary alignment tracking, daily transit updates, and astrology widgets.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PlanetaryPositionsRequest"];
                };
            };
            responses: {
                /** @description Successful planetary positions calculation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanetaryPositionsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dasha/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get current Mahadasha, Antardasha, Pratyantardasha - Dasha Calculator API
         * @description Calculate current Vimshottari Dasha periods (Mahadasha, Antardasha, Pratyantardasha) with remaining time. Accurate dasha calculator API for life phase prediction and planetary period analysis. Returns dasha timeline with start/end dates for each period. Essential for understanding current planetary influences, dasha transitions, and timing events in Vedic astrology. 120-year dasha system based on moon nakshatra at birth.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 1990 */
                        year: number;
                        /** @example 7 */
                        month: number;
                        /** @example 4 */
                        day: number;
                        /** @example 10.2 */
                        hour: number;
                        /** @example 28.6139 */
                        latitude: number;
                        /** @example 77.209 */
                        longitude: number;
                    };
                };
            };
            responses: {
                /** @description Current running dasha periods */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example 15 */
                            moonNakshatra: number;
                            /** @example Swati */
                            nakshatraName: string;
                            /**
                             * @example Rahu
                             * @enum {string}
                             */
                            nakshatraLord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                            /** @description Mahadasha period for a planet with interpretation */
                            mahadasha: {
                                /** @enum {string} */
                                planet: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                                /**
                                 * Format: date-time
                                 * @example 1990-07-04T10:12:00.000Z
                                 */
                                startDate: string;
                                /**
                                 * Format: date-time
                                 * @example 1996-07-04T10:12:00.000Z
                                 */
                                endDate: string;
                                /** @example 6 */
                                durationYears: number;
                                /** @example Sun Mahadasha brings leadership opportunities, authority, and self-expression. */
                                interpretation?: string;
                            };
                            /** @description Antardasha (sub-period) within Mahadasha */
                            antardasha: {
                                /** @enum {string} */
                                planet: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                                /**
                                 * Format: date-time
                                 * @example 1990-07-04T10:12:00.000Z
                                 */
                                startDate: string;
                                /**
                                 * Format: date-time
                                 * @example 1996-07-04T10:12:00.000Z
                                 */
                                endDate: string;
                                /** @example 6 */
                                durationYears: number;
                                /** @example Sun Mahadasha brings leadership opportunities, authority, and self-expression. */
                                interpretation?: string;
                                /** @enum {string} */
                                mahadashaLord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                            };
                            /** @description Pratyantardasha (sub-sub-period) */
                            pratyantardasha: {
                                /** @enum {string} */
                                planet: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                                /**
                                 * Format: date-time
                                 * @example 1990-07-04T10:12:00.000Z
                                 */
                                startDate: string;
                                /**
                                 * Format: date-time
                                 * @example 1996-07-04T10:12:00.000Z
                                 */
                                endDate: string;
                                /** @example 6 */
                                durationYears: number;
                                /** @example Sun Mahadasha brings leadership opportunities, authority, and self-expression. */
                                interpretation?: string;
                                /** @enum {string} */
                                mahadashaLord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                                /** @enum {string} */
                                antardashaLord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                            };
                            /**
                             * @example {
                             *       "years": 2,
                             *       "months": 4,
                             *       "days": 15,
                             *       "totalDays": 865
                             *     }
                             */
                            remainingInMahadasha: {
                                years: number;
                                months: number;
                                days: number;
                                totalDays: number;
                            };
                            /**
                             * @example {
                             *       "years": 2,
                             *       "months": 4,
                             *       "days": 15,
                             *       "totalDays": 865
                             *     }
                             */
                            remainingInAntardasha: {
                                years: number;
                                months: number;
                                days: number;
                                totalDays: number;
                            };
                            /**
                             * @example {
                             *       "years": 2,
                             *       "months": 4,
                             *       "days": 15,
                             *       "totalDays": 865
                             *     }
                             */
                            remainingInPratyantardasha: {
                                years: number;
                                months: number;
                                days: number;
                                totalDays: number;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dasha/major": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get all 9 Mahadasha periods (120-year cycle)
         * @description Returns complete Vimshottari Dasha cycle starting from birth. Shows all major planetary periods from birth through 120 years.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 1990 */
                        year: number;
                        /** @example 7 */
                        month: number;
                        /** @example 4 */
                        day: number;
                        /** @example 10.2 */
                        hour: number;
                        /** @example 28.6139 */
                        latitude: number;
                        /** @example 77.209 */
                        longitude: number;
                    };
                };
            };
            responses: {
                /** @description All 9 Mahadasha periods */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            moonNakshatra: number;
                            nakshatraName: string;
                            /** @enum {string} */
                            nakshatraLord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                            /**
                             * @description Remaining balance of first Mahadasha at birth
                             * @example {
                             *       "years": 2,
                             *       "months": 4,
                             *       "days": 15,
                             *       "totalDays": 865
                             *     }
                             */
                            birthDashaBalance: {
                                years: number;
                                months: number;
                                days: number;
                                totalDays: number;
                            };
                            /** @description All 9 Mahadasha periods in sequence */
                            mahadashas: {
                                /** @enum {string} */
                                planet: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                                /**
                                 * Format: date-time
                                 * @example 1990-07-04T10:12:00.000Z
                                 */
                                startDate: string;
                                /**
                                 * Format: date-time
                                 * @example 1996-07-04T10:12:00.000Z
                                 */
                                endDate: string;
                                /** @example 6 */
                                durationYears: number;
                                /** @example Sun Mahadasha brings leadership opportunities, authority, and self-expression. */
                                interpretation?: string;
                            }[];
                            /** @example 120 */
                            totalYears: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dasha/sub/{mahadasha}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get all Antardashas (sub-periods) for a specific Mahadasha
         * @description Returns 9 Antardasha sub-periods within a Mahadasha. Each Mahadasha is divided into 9 proportional sub-periods.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mahadasha: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 1990 */
                        year: number;
                        /** @example 7 */
                        month: number;
                        /** @example 4 */
                        day: number;
                        /** @example 10.2 */
                        hour: number;
                        /** @example 28.6139 */
                        latitude: number;
                        /** @example 77.209 */
                        longitude: number;
                    };
                };
            };
            responses: {
                /** @description Antardasha periods for specified Mahadasha */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            mahadashaLord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                            /** @description Mahadasha period for a planet with interpretation */
                            mahadashaPeriod: {
                                /** @enum {string} */
                                planet: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                                /**
                                 * Format: date-time
                                 * @example 1990-07-04T10:12:00.000Z
                                 */
                                startDate: string;
                                /**
                                 * Format: date-time
                                 * @example 1996-07-04T10:12:00.000Z
                                 */
                                endDate: string;
                                /** @example 6 */
                                durationYears: number;
                                /** @example Sun Mahadasha brings leadership opportunities, authority, and self-expression. */
                                interpretation?: string;
                            };
                            antardashas: {
                                /** @enum {string} */
                                planet: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                                /**
                                 * Format: date-time
                                 * @example 1990-07-04T10:12:00.000Z
                                 */
                                startDate: string;
                                /**
                                 * Format: date-time
                                 * @example 1996-07-04T10:12:00.000Z
                                 */
                                endDate: string;
                                /** @example 6 */
                                durationYears: number;
                                /** @example Sun Mahadasha brings leadership opportunities, authority, and self-expression. */
                                interpretation?: string;
                                /** @enum {string} */
                                mahadashaLord: "Ketu" | "Venus" | "Sun" | "Moon" | "Mars" | "Rahu" | "Jupiter" | "Saturn" | "Mercury";
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panchang/basic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get basic Panchang - Tithi Nakshatra Yoga Karana Calculator
         * @description Calculate Panchang elements (Hindu calendar) for any date: Tithi (lunar day), Nakshatra (lunar mansion), Yoga, and Karana. Daily panchang API for determining auspicious timings (muhurta), festival dates, and planetary influences. Tithi calculator with Shukla/Krishna paksha. Accurate nakshatra today with ruling planet. Essential for Hindu calendar integration, muhurta selection, and Vedic timekeeping in astrology apps.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @example 2025 */
                        year: number;
                        /** @example 12 */
                        month: number;
                        /** @example 17 */
                        day: number;
                        /** @example 12 */
                        hour: number;
                        /** @example 28.6139 */
                        latitude: number;
                        /** @example 77.209 */
                        longitude: number;
                    };
                };
            };
            responses: {
                /** @description Panchang elements calculated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Lunar day (tithi) information with interpretations */
                            tithi: {
                                number: number;
                                name: string;
                                /** @enum {string} */
                                paksha: "Shukla" | "Krishna";
                                percent: number;
                                /** @example Vishnu */
                                deity?: string;
                                /** @example Sun */
                                rulingPlanet?: string;
                                /** @example Fire */
                                element?: string;
                            };
                            /** @description Nakshatra (lunar mansion) information with interpretations */
                            nakshatra: {
                                number: number;
                                name: string;
                                lord: string;
                                /** @example Ashwini Kumaras */
                                deity?: string;
                                /** @example Horse Head */
                                symbol?: string;
                                /** @example Quick, healing energy */
                                characteristics?: string;
                            };
                            /** @description Yoga information with characteristics */
                            yoga: {
                                number: number;
                                name: string;
                                /** @example Auspicious for new beginnings */
                                characteristics?: string;
                            };
                            /** @description Karana (half-tithi) information with characteristics */
                            karana: {
                                number: number;
                                name: string;
                                /** @example Movable */
                                type?: string;
                                /** @example Good for travel and movement */
                                characteristics?: string;
                            };
                            /** @example 265.42 */
                            sunLongitude: number;
                            /** @example 315.67 */
                            moonLongitude: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dosha/manglik": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Manglik Dosha - Mangal Dosha Calculator API
         * @description Detect Manglik dosha (Kuja dosha, Mars dosha) based on Mars position in inauspicious houses (1, 2, 4, 7, 8, 12) from Lagna. Accurate mangal dosha calculator for matrimonial compatibility checks in Vedic astrology. Returns severity levels (Mild/Moderate/Severe) and cancellation factors. Essential for kundli matching for marriage, manglik compatibility, and marriage astrology in matrimonial sites. Includes exceptions that reduce manglik dosha effects.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ManglikRequest"];
                };
            };
            responses: {
                /** @description Manglik dosha analysis */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ManglikResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dosha/kalsarpa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Kalsarpa Dosha - Kalsarpa Yoga Calculator API
         * @description Detect Kalsarpa dosha (Kalsarpa yoga) when all 7 planets are hemmed between Rahu-Ketu axis. Accurate kalsarpa dosha calculator identifying 12 types (Ananta, Kulik, Vasuki, Shankhapala, Padma, Mahapadma, Takshak, Karkotak, Shankhnaad, Patak, Vishdhar, Shesh). Returns severity and effects based on Rahu house position. Essential for Vedic astrology dosha analysis, birth chart evaluation, and matrimonial compatibility. Considered significant dosha affecting life obstacles and spiritual growth.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["KalsarpaRequest"];
                };
            };
            responses: {
                /** @description Kalsarpa dosha analysis */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KalsarpaResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dosha/sadhesati": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Sadhesati - Sade Sati Calculator API (Saturn Transit)
         * @description Calculate Sadhesati (Sade Sati) periods when Saturn transits 12th, 1st, and 2nd houses from natal Moon. Accurate sade sati calculator with current status and phase identification (Rising/Peak/Setting). Shani sadhesati 7.5 year period tracker. Returns Saturn transit dates and effects on life. Essential for Saturn transit analysis, sadhesati remedies timing, and understanding challenging Saturn periods in Vedic astrology. Important for timing major life decisions.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SadhesatiRequest"];
                };
            };
            responses: {
                /** @description Sadhesati period analysis */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SadhesatiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoga": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all planetary yogas - 300+ Vedic Yoga Combinations
         * @description Returns list of all 300+ planetary yogas (astrological combinations) with basic information (id and name only). Use this to discover available yogas, then call GET /yogas/:id for detailed information. Perfect for building yoga browser interfaces, search functionality, and progressive data loading in astrology apps.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of all yogas (basic info) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description List of yoga IDs and names */
                            yogas: {
                                /** @example gajakesari */
                                id: string;
                                /** @example Gajakesari Yoga */
                                name: string;
                            }[];
                            /** @example 300 */
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yoga/:id": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get yoga details by ID - Detailed Yoga Information API
         * @description Returns complete details for a specific yoga including formation conditions, results/effects, and quality (Positive/Negative/Both). Use GET /yogas first to get the list of IDs. Provides in-depth information about each planetary combination. Perfect for yoga detail pages, educational content, and astrological interpretation in horoscope apps.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Yoga identifier (lowercase, hyphenated) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Detailed yoga information */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example gajakesari */
                            id: string;
                            /** @example Gajakesari Yoga */
                            name: string;
                            /** @example Jupiter in kendra from Moon */
                            description: string;
                            /** @example Gajakesari Yoga is one of the most powerful yogas. You will be eloquent, wealthy... */
                            result: string;
                            /**
                             * @example Positive
                             * @enum {string}
                             */
                            quality: "Positive" | "Negative" | "Both";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kp/ayanamsa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get KP-Newcomb ayanamsa - Dynamic daily calculation
         * @description Get real-time KP-Newcomb ayanamsa value calculated using Newcomb precession theory - no preset tables. Returns precise ayanamsa for any date based on IAU modern precession standards. Essential for accurate KP chart calculations and research. Formula: A = 16.90709×(Year/10000) - 0.757371×(Year/1000)² - 6.92416, B = (Month-1 + Date/30)×1.1574074/1000. KP Newcomb ayanamsa API, dynamic ayanamsa calculator, Krishnamurti ayanamsa today, current KP ayanamsa
         */
        get: {
            parameters: {
                query?: {
                    /** @description Date for ayanamsa calculation in YYYY-MM-DD format. Defaults to today if not provided. Ayanamsa changes by ~0.01° per month due to Earth's precession. */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successfully calculated KP-Newcomb ayanamsa */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KPAyanamsaResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kp/planets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get KP planetary positions with sub-lords
         * @description Get planetary positions with detailed KP star-lord and sub-lord calculations for precise event timing and significator analysis. Returns all 9 planets (Sun through Ketu) with nakshatra, star-lord, sub-lord, and KP horary numbers (1-249). Essential for KP astrology software, significator analysis, and event prediction. KP planet positions API, star lord sub lord calculator, KP significator API, Krishnamurti Paddhati planets
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["KPPlanetsRequest"];
                };
            };
            responses: {
                /** @description Successfully calculated KP planetary positions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KPPlanetsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kp/cusps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Placidus house cusps with sub-lords
         * @description Calculate unequal Placidus house cusps with ruling sign-lord, nakshatra-lord, and sub-lord for each cusp. Dynamic KP-Newcomb or custom ayanamsa support. Used in KP horary astrology, cusp sub-lord analysis, and birth chart rectification. Returns all 12 house cusps with KP sub-division details. SEO: Placidus house cusps API, KP cusp calculator, house cusps star sub lord, KP horary cusps
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["KPCuspsRequest"];
                };
            };
            responses: {
                /** @description Successfully calculated Placidus house cusps */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KPCuspsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/kp/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate complete KP birth chart
         * @description Generate authentic Krishnamurti Paddhati birth charts with Placidus house cusps, star-lord and sub-lord calculations. Supports custom ayanamsa and dynamic KP-Newcomb ayanamsa calculation. Returns complete chart with all 9 planets (Sun through Ketu), Ascendant, 12 Placidus house cusps, nakshatra details, star-lords, sub-lords, and KP horary numbers (1-249). Perfect for KP astrology software, horary prediction apps, and event timing analysis. SEO: KP astrology chart API, Placidus house cusps planets, Krishnamurti Paddhati chart generator, KP birth chart calculator
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["KPChartRequest"];
                };
            };
            responses: {
                /** @description Successfully generated KP birth chart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KPChartResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "aries": {
         *         "rashi": "aries",
         *         "signs": []
         *       },
         *       "meta": {
         *         "Sun": {
         *           "graha": "Sun",
         *           "rashi": "Leo",
         *           "longitude": 132.45,
         *           "nakshatra": {
         *             "name": "Magha",
         *             "pada": 2,
         *             "key": 9
         *           },
         *           "isRetrograde": false
         *         },
         *         "Moon": {
         *           "graha": "Moon",
         *           "rashi": "Cancer",
         *           "longitude": 98.32,
         *           "nakshatra": {
         *             "name": "Punarvasu",
         *             "pada": 4,
         *             "key": 6
         *           },
         *           "isRetrograde": false
         *         }
         *       }
         *     }
         */
        BirthChartResponse: {
            aries: {
                rashi: string;
                signs: {
                    graha: string;
                    longitude: number;
                    nakshatra: {
                        name: string;
                        pada: number;
                        key: number;
                    };
                    isRetrograde: boolean;
                }[];
            };
            meta: {
                [key: string]: {
                    graha: string;
                    rashi: string;
                    longitude: number;
                    nakshatra: {
                        name: string;
                        pada: number;
                        key: number;
                    };
                    isRetrograde: boolean;
                };
            };
        };
        BirthChartRequest: {
            /**
             * Format: date
             * @description Birth date in YYYY-MM-DD format. Date determines planetary positions and nakshatra calculations for Vedic kundli (janam patri). Accurate birth date is essential for dashas, yoga calculations, and divisional charts (vargas).
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in 24-hour HH:MM:SS format. Time is CRITICAL for Lagna (Ascendant) calculation and house divisions - changes every ~2 hours. Even minutes matter for accurate nakshatra pada and divisional chart (D9, D10) calculations. Without exact time, Lagna and house-based predictions will be incorrect.
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude in decimal degrees. Location determines local sidereal time for Lagna calculation and affects bhava (house) cusps. Example: Delhi 28.6139, Mumbai 19.0760, Kathmandu 27.7172.
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude in decimal degrees. Affects local time calculations and ayanamsha adjustments. Example: Delhi 77.2090, Mumbai 72.8777, Kathmandu 85.3240.
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in decimal hours (NOT minutes format). Negative for west of UTC, positive for east. Examples: India IST = 5.5 (NOT 5:30), Nepal NPT = 5.75 (NOT 5:45), New York EST = -5. IMPORTANT: Use decimal format (5.5, not 5:30). Server timezone does NOT affect results - calculations are timezone-independent.
             * @example 5.5
             */
            timezone: number;
        };
        NavamsaResponse: {
            /** @description Navamsa chart with same structure as birth chart */
            chart?: unknown;
            /**
             * @description Planets that are Vargottama (same sign in D1 and D9)
             * @example [
             *       "Sun",
             *       "Moon"
             *     ]
             */
            vargottama: string[];
            /**
             * @description Explanation of Vargottama significance
             * @example Vargottama planets occupy the same zodiac sign in both D1 (birth chart) and D9 (Navamsa chart), indicating exceptional strength and purity. These planets deliver their full results with minimal affliction, bringing stability and success in their significations. Vargottama is considered highly auspicious, especially for benefics like Jupiter and Venus, as it doubles the positive effects in marriage, spirituality, and overall life prosperity.
             */
            vargottamaExplanation: string;
        };
        NavamsaRequest: {
            /**
             * Format: date
             * @description Birth date in YYYY-MM-DD format. Date determines planetary positions and nakshatra calculations for Vedic kundli (janam patri). Accurate birth date is essential for dashas, yoga calculations, and divisional charts (vargas).
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in 24-hour HH:MM:SS format. Time is CRITICAL for Lagna (Ascendant) calculation and house divisions - changes every ~2 hours. Even minutes matter for accurate nakshatra pada and divisional chart (D9, D10) calculations. Without exact time, Lagna and house-based predictions will be incorrect.
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude in decimal degrees. Location determines local sidereal time for Lagna calculation and affects bhava (house) cusps. Example: Delhi 28.6139, Mumbai 19.0760, Kathmandu 27.7172.
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude in decimal degrees. Affects local time calculations and ayanamsha adjustments. Example: Delhi 77.2090, Mumbai 72.8777, Kathmandu 85.3240.
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in decimal hours (NOT minutes format). Negative for west of UTC, positive for east. Examples: India IST = 5.5 (NOT 5:30), Nepal NPT = 5.75 (NOT 5:45), New York EST = -5. IMPORTANT: Use decimal format (5.5, not 5:30). Server timezone does NOT affect results - calculations are timezone-independent.
             * @example 5.5
             */
            timezone: number;
        };
        CompatibilityResponse: {
            /**
             * @description Total compatibility score
             * @example 24.5
             */
            total: number;
            /**
             * @description Maximum possible score
             * @example 36
             */
            maxScore: number;
            /**
             * @description Compatibility percentage
             * @example 68.1
             */
            percentage: number;
            /**
             * @description Compatible if >= 50%
             * @example true
             */
            isCompatible: boolean;
            /**
             * @description Detailed breakdown of compatibility scores across 8 categories: Nakshatra (4), Gana (6), Yoni (4), Rashi Lord (5), Vasya (2), Tara (3), Nadi (8), Bhakoot (7)
             * @example [
             *       {
             *         "category": "Nakshatra",
             *         "score": 4,
             *         "description": "Excellent nakshatra match"
             *       },
             *       {
             *         "category": "Gana",
             *         "score": 6,
             *         "description": "Perfect temperament match"
             *       },
             *       {
             *         "category": "Yoni",
             *         "score": 2,
             *         "description": "Moderate nature compatibility"
             *       }
             *     ]
             */
            breakdown: {
                /** @example Nakshatra */
                category: string;
                /** @example 4 */
                score: number;
                /** @example Nakshatra compatibility based on birth stars */
                description: string;
            }[];
        };
        CompatibilityRequest: {
            /** @description First person birth data */
            person1: {
                /**
                 * Format: date
                 * @description Birth date in YYYY-MM-DD format. Date determines planetary positions and nakshatra calculations for Vedic kundli (janam patri). Accurate birth date is essential for dashas, yoga calculations, and divisional charts (vargas).
                 * @example 1990-07-04
                 */
                date: string;
                /**
                 * @description Birth time in 24-hour HH:MM:SS format. Time is CRITICAL for Lagna (Ascendant) calculation and house divisions - changes every ~2 hours. Even minutes matter for accurate nakshatra pada and divisional chart (D9, D10) calculations. Without exact time, Lagna and house-based predictions will be incorrect.
                 * @example 10:12:00
                 */
                time: string;
                /**
                 * @description Birth location latitude in decimal degrees. Location determines local sidereal time for Lagna calculation and affects bhava (house) cusps. Example: Delhi 28.6139, Mumbai 19.0760, Kathmandu 27.7172.
                 * @example 28.6139
                 */
                latitude: number;
                /**
                 * @description Birth location longitude in decimal degrees. Affects local time calculations and ayanamsha adjustments. Example: Delhi 77.2090, Mumbai 72.8777, Kathmandu 85.3240.
                 * @example 77.209
                 */
                longitude: number;
                /**
                 * @description Timezone offset from UTC in decimal hours (NOT minutes format). Negative for west of UTC, positive for east. Examples: India IST = 5.5 (NOT 5:30), Nepal NPT = 5.75 (NOT 5:45), New York EST = -5. IMPORTANT: Use decimal format (5.5, not 5:30). Server timezone does NOT affect results - calculations are timezone-independent.
                 * @example 5.5
                 */
                timezone: number;
            };
            /** @description Second person birth data */
            person2: {
                /**
                 * Format: date
                 * @description Birth date in YYYY-MM-DD format. Date determines planetary positions and nakshatra calculations for Vedic kundli (janam patri). Accurate birth date is essential for dashas, yoga calculations, and divisional charts (vargas).
                 * @example 1990-07-04
                 */
                date: string;
                /**
                 * @description Birth time in 24-hour HH:MM:SS format. Time is CRITICAL for Lagna (Ascendant) calculation and house divisions - changes every ~2 hours. Even minutes matter for accurate nakshatra pada and divisional chart (D9, D10) calculations. Without exact time, Lagna and house-based predictions will be incorrect.
                 * @example 10:12:00
                 */
                time: string;
                /**
                 * @description Birth location latitude in decimal degrees. Location determines local sidereal time for Lagna calculation and affects bhava (house) cusps. Example: Delhi 28.6139, Mumbai 19.0760, Kathmandu 27.7172.
                 * @example 28.6139
                 */
                latitude: number;
                /**
                 * @description Birth location longitude in decimal degrees. Affects local time calculations and ayanamsha adjustments. Example: Delhi 77.2090, Mumbai 72.8777, Kathmandu 85.3240.
                 * @example 77.209
                 */
                longitude: number;
                /**
                 * @description Timezone offset from UTC in decimal hours (NOT minutes format). Negative for west of UTC, positive for east. Examples: India IST = 5.5 (NOT 5:30), Nepal NPT = 5.75 (NOT 5:45), New York EST = -5. IMPORTANT: Use decimal format (5.5, not 5:30). Server timezone does NOT affect results - calculations are timezone-independent.
                 * @example 5.5
                 */
                timezone: number;
            };
        };
        /**
         * @example {
         *       "Sun": {
         *         "graha": "Sun",
         *         "rashi": "Leo",
         *         "longitude": 132.45,
         *         "nakshatra": {
         *           "name": "Magha",
         *           "pada": 2,
         *           "key": 9,
         *           "deity": "Pitris (Ancestors)",
         *           "symbol": "Royal Throne",
         *           "characteristics": "Leadership, ancestral pride, regal nature"
         *         },
         *         "rashiDetails": {
         *           "vedicName": "Simha",
         *           "symbol": "Lion",
         *           "energy": "Masculine, Fire",
         *           "characteristics": "Natural leadership, confidence, creativity"
         *         },
         *         "isRetrograde": false
         *       },
         *       "Moon": {
         *         "graha": "Moon",
         *         "rashi": "Cancer",
         *         "longitude": 98.32,
         *         "nakshatra": {
         *           "name": "Punarvasu",
         *           "pada": 4,
         *           "key": 6,
         *           "deity": "Aditi",
         *           "symbol": "Bow and Quiver",
         *           "characteristics": "Renewal, optimism, spiritual growth"
         *         },
         *         "rashiDetails": {
         *           "vedicName": "Karka",
         *           "symbol": "Crab",
         *           "energy": "Feminine, Water",
         *           "characteristics": "Nurturing, emotional depth, protective"
         *         },
         *         "isRetrograde": false
         *       }
         *     }
         */
        PlanetaryPositionsResponse: {
            [key: string]: {
                /** @example Sun */
                graha: string;
                /** @example Leo */
                rashi: string;
                /** @example 132.45 */
                longitude: number;
                nakshatra: {
                    /** @example Magha */
                    name: string;
                    /** @example 2 */
                    pada: number;
                    /** @example 9 */
                    key: number;
                    /** @example Pitris (Ancestors) */
                    deity?: string;
                    /** @example Royal Throne */
                    symbol?: string;
                    /** @example Leadership qualities... */
                    characteristics?: string;
                };
                rashiDetails?: {
                    /** @example Simha */
                    vedicName?: string;
                    /** @example Lion */
                    symbol?: string;
                    /** @example Masculine, Fire */
                    energy?: string;
                    /** @example Natural leadership... */
                    characteristics?: string;
                };
                /** @example false */
                isRetrograde: boolean;
            };
        };
        PlanetaryPositionsRequest: {
            /**
             * Format: date
             * @description Birth date in YYYY-MM-DD format. Date determines planetary positions and nakshatra calculations for Vedic kundli (janam patri). Accurate birth date is essential for dashas, yoga calculations, and divisional charts (vargas).
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in 24-hour HH:MM:SS format. Time is CRITICAL for Lagna (Ascendant) calculation and house divisions - changes every ~2 hours. Even minutes matter for accurate nakshatra pada and divisional chart (D9, D10) calculations. Without exact time, Lagna and house-based predictions will be incorrect.
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude in decimal degrees. Location determines local sidereal time for Lagna calculation and affects bhava (house) cusps. Example: Delhi 28.6139, Mumbai 19.0760, Kathmandu 27.7172.
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude in decimal degrees. Affects local time calculations and ayanamsha adjustments. Example: Delhi 77.2090, Mumbai 72.8777, Kathmandu 85.3240.
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in decimal hours (NOT minutes format). Negative for west of UTC, positive for east. Examples: India IST = 5.5 (NOT 5:30), Nepal NPT = 5.75 (NOT 5:45), New York EST = -5. IMPORTANT: Use decimal format (5.5, not 5:30). Server timezone does NOT affect results - calculations are timezone-independent.
             * @example 5.5
             */
            timezone: number;
        };
        ManglikResponse: {
            /**
             * @description Whether the dosha is present
             * @example true
             */
            present: boolean;
            /**
             * @description Severity level of the dosha
             * @example Moderate
             * @enum {string}
             */
            severity?: "Mild" | "Moderate" | "Severe";
            /**
             * @description Type or phase of the dosha
             * @example Ananta Kalsarpa
             */
            type?: string;
            /**
             * @description Detailed description of the dosha
             * @example Manglik Dosha present. Mars in house 7 creates matrimonial afflictions.
             */
            description: string;
            /**
             * @description Exceptions or cancellations that reduce severity
             * @example [
             *       "Mars in own sign (reduces severity)"
             *     ]
             */
            exceptions?: string[];
        };
        ManglikRequest: {
            /**
             * Format: date
             * @description Birth date in YYYY-MM-DD format
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in HH:MM:SS format (24-hour)
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in hours (e.g., 5.5 for IST)
             * @example 5.5
             */
            timezone: number;
        };
        KalsarpaResponse: {
            /**
             * @description Whether the dosha is present
             * @example true
             */
            present: boolean;
            /**
             * @description Severity level of the dosha
             * @example Moderate
             * @enum {string}
             */
            severity?: "Mild" | "Moderate" | "Severe";
            /**
             * @description Type or phase of the dosha
             * @example Ananta Kalsarpa
             */
            type?: string;
            /**
             * @description Detailed description of the dosha
             * @example Manglik Dosha present. Mars in house 7 creates matrimonial afflictions.
             */
            description: string;
            /**
             * @description Exceptions or cancellations that reduce severity
             * @example [
             *       "Mars in own sign (reduces severity)"
             *     ]
             */
            exceptions?: string[];
        };
        KalsarpaRequest: {
            /**
             * Format: date
             * @description Birth date in YYYY-MM-DD format
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in HH:MM:SS format (24-hour)
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in hours (e.g., 5.5 for IST)
             * @example 5.5
             */
            timezone: number;
        };
        SadhesatiResponse: {
            /**
             * @description Whether the dosha is present
             * @example true
             */
            present: boolean;
            /**
             * @description Severity level of the dosha
             * @example Moderate
             * @enum {string}
             */
            severity?: "Mild" | "Moderate" | "Severe";
            /**
             * @description Type or phase of the dosha
             * @example Ananta Kalsarpa
             */
            type?: string;
            /**
             * @description Detailed description of the dosha
             * @example Manglik Dosha present. Mars in house 7 creates matrimonial afflictions.
             */
            description: string;
            /**
             * @description Exceptions or cancellations that reduce severity
             * @example [
             *       "Mars in own sign (reduces severity)"
             *     ]
             */
            exceptions?: string[];
        };
        SadhesatiRequest: {
            /**
             * Format: date
             * @description Birth date in YYYY-MM-DD format
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in HH:MM:SS format (24-hour)
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in hours (e.g., 5.5 for IST)
             * @example 5.5
             */
            timezone: number;
        };
        KPAyanamsaResponse: {
            /**
             * @description Date for which ayanamsa was calculated
             * @example 2025-12-26
             */
            date: string;
            /**
             * @description KP-Newcomb ayanamsa value in degrees
             * @example 24.22233926
             */
            ayanamsa: number;
            /**
             * @description Ayanamsa type identifier
             * @example kp-newcomb
             */
            type: string;
            /**
             * @description Mathematical basis for ayanamsa calculation
             * @example Newcomb precession theory
             */
            formula: string;
            /**
             * @description UTC timestamp when calculation was performed
             * @example 2025-12-26T10:30:00Z
             */
            calculated: string;
        };
        KPPlanetsResponse: {
            /**
             * @description Applied ayanamsa value in degrees
             * @example 24.22233926
             */
            ayanamsa: number;
            planets: {
                /**
                 * @description Planet name
                 * @example Sun
                 */
                planet: string;
                /**
                 * @description Sidereal ecliptic longitude (0-360°)
                 * @example 108.23
                 */
                longitude: number;
                /**
                 * @description Zodiac sign
                 * @example Cancer
                 */
                sign: string;
                /**
                 * @description Ruling planet of the sign
                 * @example Moon
                 */
                signLord: string;
                /**
                 * @description Nakshatra (lunar mansion)
                 * @example Pushya
                 */
                nakshatra: string;
                /**
                 * @description Nakshatra number (1-27)
                 * @example 8
                 */
                nakshatraNumber: number;
                /**
                 * @description Nakshatra ruling planet
                 * @example Saturn
                 */
                nakshatraLord: string;
                /**
                 * @description Nakshatra pada/quarter (1-4)
                 * @example 2
                 */
                pada: number;
                /**
                 * @description Star-lord (same as nakshatra lord in KP system)
                 * @example Saturn
                 */
                starLord: string;
                /**
                 * @description Sub-lord based on 249-level KP subdivision
                 * @example Mercury
                 */
                subLord: string;
                /**
                 * @description KP horary number (1-249)
                 * @example 45
                 */
                kpNumber: number;
                /**
                 * @description Whether planet is in retrograde motion
                 * @example false
                 */
                retrograde: boolean;
            }[];
        };
        KPPlanetsRequest: {
            /**
             * @description Birth date in YYYY-MM-DD format
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in 24-hour HH:MM:SS format
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude in decimal degrees
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude in decimal degrees
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in decimal hours
             * @example 5.5
             */
            timezone: number;
            /**
             * @description Ayanamsa type: "kp-newcomb" for dynamic calculation or "custom" to provide your own value
             * @example kp-newcomb
             * @enum {string}
             */
            ayanamsa: "kp-newcomb" | "custom";
            /**
             * @description Custom ayanamsa value in degrees (required if ayanamsa="custom")
             * @example 24
             */
            ayanamsaValue?: number;
        };
        KPCuspsResponse: {
            /**
             * @description Applied ayanamsa value in degrees
             * @example 24
             */
            ayanamsa: number;
            /**
             * @description House system used for calculations
             * @example placidus
             */
            houseSystem: string;
            cusps: {
                /**
                 * @description House number (1-12)
                 * @example 1
                 */
                house: number;
                /**
                 * @description Cusp longitude in degrees (0-360)
                 * @example 89.45
                 */
                longitude: number;
                /**
                 * @description Zodiac sign of the cusp
                 * @example Cancer
                 */
                sign: string;
                /**
                 * @description Ruling planet of the sign
                 * @example Moon
                 */
                signLord: string;
                /**
                 * @description Nakshatra at cusp position
                 * @example Ashlesha
                 */
                nakshatra: string;
                /**
                 * @description Nakshatra ruling planet
                 * @example Mercury
                 */
                nakshatraLord: string;
                /**
                 * @description Nakshatra pada/quarter (1-4)
                 * @example 3
                 */
                pada: number;
                /**
                 * @description Star-lord (nakshatra lord)
                 * @example Mercury
                 */
                starLord: string;
                /**
                 * @description Sub-lord based on KP 249-level subdivision
                 * @example Venus
                 */
                subLord: string;
                /**
                 * @description KP horary number (1-249)
                 * @example 32
                 */
                kpNumber: number;
            }[];
        };
        KPCuspsRequest: {
            /**
             * @description Birth date in YYYY-MM-DD format
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in 24-hour HH:MM:SS format
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude in decimal degrees
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude in decimal degrees
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in decimal hours
             * @example 5.5
             */
            timezone: number;
            /**
             * @description Ayanamsa type: "kp-newcomb" for dynamic calculation or "custom" for custom value
             * @example kp-newcomb
             * @enum {string}
             */
            ayanamsa: "kp-newcomb" | "custom";
            /**
             * @description Custom ayanamsa value in degrees (required if ayanamsa="custom")
             * @example 24
             */
            ayanamsaValue?: number;
        };
        KPChartResponse: {
            meta: {
                date: string;
                time: string;
                latitude: number;
                longitude: number;
                timezone: number;
                ayanamsa: number;
                ayanamsaType: string;
                houseSystem: string;
            };
            ascendant: {
                longitude: number;
                sign: string;
                nakshatra: string;
                nakshatraLord: string;
                pada: number;
                starLord: string;
                subLord: string;
                kpNumber: number;
            };
            cusps: {
                house: number;
                longitude: number;
                sign: string;
                signLord: string;
                nakshatra: string;
                nakshatraLord: string;
                pada: number;
                starLord: string;
                subLord: string;
                kpNumber: number;
            }[];
            planets: {
                planet: string;
                longitude: number;
                sign: string;
                house: number;
                nakshatra: string;
                nakshatraLord: string;
                pada: number;
                starLord: string;
                subLord: string;
                kpNumber: number;
                retrograde: boolean;
            }[];
            nodes: {
                rahu: {
                    longitude: number;
                    sign: string;
                    house: number;
                    nakshatra: string;
                    starLord: string;
                    subLord: string;
                };
                ketu: {
                    longitude: number;
                    sign: string;
                    house: number;
                    nakshatra: string;
                    starLord: string;
                    subLord: string;
                };
            };
        };
        KPChartRequest: {
            /**
             * @description Birth date in YYYY-MM-DD format
             * @example 1990-07-04
             */
            date: string;
            /**
             * @description Birth time in 24-hour HH:MM:SS format. CRITICAL for accurate Lagna and house calculations.
             * @example 10:12:00
             */
            time: string;
            /**
             * @description Birth location latitude in decimal degrees
             * @example 28.6139
             */
            latitude: number;
            /**
             * @description Birth location longitude in decimal degrees
             * @example 77.209
             */
            longitude: number;
            /**
             * @description Timezone offset from UTC in decimal hours (e.g., India IST = 5.5)
             * @example 5.5
             */
            timezone: number;
            /**
             * @description Ayanamsa type: "kp-newcomb" for dynamic KP-Newcomb calculation or "custom" for custom value
             * @example kp-newcomb
             * @enum {string}
             */
            ayanamsa: "kp-newcomb" | "custom";
            /**
             * @description Custom ayanamsa value in degrees (required if ayanamsa="custom")
             * @example 24
             */
            ayanamsaValue?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
